### ISSUE TITLE
Sweep: create an empty sweep.yaml file

### ISSUE THREAD

**Issue by Fede-26** [Fede-26/sap-1-fpga#2]

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
HypraFission, @aitorct, @coco163, @0O7UMXiu5hxujBzw, @JDDCN, @Jmchin, @biblia19, @0xtlt, @marstau, @MarwanNour, @trevor-vincent, @ramchandracheke, @quangv, @LucasSnatiago, @ymero, @RamonRomeroQro, @viasnake, @pmsoltani, @ojczeo, @xxrougexx, @shubham23596, @mo-han, @32x-k, @yadinae, @nathgilson, @zjkanjie, @r0073d-l053r, @RadonX, @Derimax3, @hangfeng, @letterknumber9, @Gaoshengyue, @panzhaohui, @JusCallMeRico, @davidbrandpro, @li-xunhuan, @PrestonKnopp, @90stripverse, @SunShRui, @sp46290, @frankhuurman, @dytan, @sky-code, @csli, @Ta180m, @Indieaner, @tangdou1, @gnhzww, @themagiulio, @cklx0719

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lynnboy, @tatapbl4, @ModerRAS, @sourabh1407, @sreyaschaithanya, @botto, @SKR4PS, @000HuangWenfeng000, @imikay, @whatofit, @xucongyong, @siralanjoshua86, @alanapost, @KrishnaPG, @mig38m, @jaffwu, @kaid, @maveray, @Hexidaz, @aamorozov, @satoshi-nakamoto420, @MaxQi, @hl, @Ledjob, @Yakulu, @caladanY, @qintang, @randylien, @hzdlive, @HUEGG-birdy, @vmotso, @fastlanecabbie, @ccyanxyz, @borankux, @cnsdhzzl, @lyriarte, @tonyseek, @Yanyuanqianjia, @tdkr, @jieyoung, @LoverKalay, @lewlh, @s3d1k, @MahmoudDolah, @va511e, @crvdgc, @iczc, @SealJia, @CGeekhl, @unicorn343

**Comment by crvdgc** [comment]
Why the fuck are you sending ads through GitHub? Don't ever do this.
